language: c

env:
  global:
    - NODE_PATH=/home/travis/xtuple-server/node_modules

before_install:
  - cd /home/travis
  - wget xtuple.com/bootstrap -qO- | sudo bash
  - git clone https://github.com/xtuple/xtuple-server-core.git
  - git clone https://github.com/xtuple/xtuple-server.git

install:
  - cd xtuple-server-core
  - npm install
  - cd ../xtuple-server
  - npm install

script:
  - cd ../xtuple-server-core
  - sudo -E bash -c 'echo $NODE_PATH'
  - sudo -E node ./cli.js setup
  - cd ../xtuple-server
  - sudo -E npm test
  - sudo -E npm test
