language: c

before_install:
  - wget xtuple.com/bootstrap -qO- | sudo bash
  - cd ..
  - git clone https://github.com/shackbarth/xtuple-server-core.git
  - git clone https://github.com/shackbarth/xtuple-server.git

install:
  - cd xtuple-server-core
  - npm install
  - cd ../xtuple-server
  - npm install
  - npm link ../xtuple-server-core/lib
  - npm link ../xtuple-server-core
  - rm index.js
  - cp ../xtuple-server-core/index.js .
  - cp ../xtuple-server-core/cli.js .
  - cd ../xtuple-server-core
  - npm link ../xtuple-server/tasks/pg/tuner
  - npm link ../xtuple-server/tasks/pg/snapshotmgr
  - npm link ../xtuple-server/tasks/sys/cups
  - npm link ../xtuple-server/tasks/sys/paths
  - npm link ../xtuple-server/tasks/sys/policy
  - npm link ../xtuple-server/tasks/sys/service
  - npm link ../xtuple-server/tasks/sys/ssh
  - npm link ../xtuple-server/tasks/sys/webmin
  - npm link ../xtuple-server/tasks/sys/xvfb

script:
  - cd ../xtuple-server
  - ls -l plans
  - sudo node ./cli.js install-pilot --xt-version 4.8.0 --xt-name aurora --pg-capacity 64 --xt-quickstart
